{"uid":"d1b6330e6d0136","name":"test_send_and_delete_message_1_with_attachment[chrome]","fullName":"test_DiscordFrontEnd.TestDiscordMessageActions#test_send_and_delete_message_1_with_attachment","historyId":"0f56ca217fa9e43089179bf211355525","time":{"start":1730128702900,"stop":1730128702900,"duration":0},"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me","statusTrace":"self = <login_page.LoginPage object at 0x7f6331483f70>\n\n    @allure.step(\"Проверка перехода на страницу каналов\")\n    def verify_login_success(self):\n        try:\n>           self.wait_for_url_to_be(LoginPage.CHANNELS_URL, timeout=20)\n\nlogin_page.py:55: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nlogin_page.py:90: in wait_for_url_to_be\n    WebDriverWait(self.driver, timeout).until(EC.url_to_be(url))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"9a7727a07998286cc9dc9bab69a00dab\")>\nmethod = <function url_to_be.<locals>._predicate at 0x7f6331aea8c0>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9a7727a07998286cc9dc9bab69a00dab\")>\n\n    @pytest.fixture(scope=\"class\", autouse=True)\n    def setup(driver):\n        login_page = LoginPage(driver)\n    \n        with allure.step(\"Открытие страницы логина\"):\n            login_page.open(\"https://discord.com/login\")\n    \n            if not login_page.is_element_visible(LoginPage.EMAIL_INPUT):\n                raise AssertionError(\"Поле для ввода email не найдено.\")\n    \n        with allure.step(\"Вход в систему\"):\n>           login_page.login()\n\nconftest.py:58: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nlogin_page.py:45: in login\n    self.verify_login_success()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <login_page.LoginPage object at 0x7f6331483f70>\n\n    @allure.step(\"Проверка перехода на страницу каналов\")\n    def verify_login_success(self):\n        try:\n            self.wait_for_url_to_be(LoginPage.CHANNELS_URL, timeout=20)\n            print(f\"Успешный вход: переход на {LoginPage.CHANNELS_URL}\")\n        except TimeoutException:\n            print(\"Ошибка: Не удалось перейти на страницу каналов после логина\")\n            self.take_screenshot(\"login_failed\")\n>           raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\nE           AssertionError: Не удалось перейти на https://discord.com/channels/@me\n\nlogin_page.py:60: AssertionError","flaky":false,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1730128702901,"stop":1730128713348,"duration":10447},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup","time":{"start":1730128713349,"stop":1730128746314,"duration":32965},"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/conftest.py\", line 58, in setup\n    login_page.login()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 45, in login\n    self.verify_login_success()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 60, in verify_login_success\n    raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\n","steps":[{"name":"Открытие страницы логина","time":{"start":1730128713349,"stop":1730128717330,"duration":3981},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Вход в систему","time":{"start":1730128717330,"stop":1730128746314,"duration":28984},"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me\n","statusTrace":"  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/conftest.py\", line 58, in setup\n    login_page.login()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 45, in login\n    self.verify_login_success()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 60, in verify_login_success\n    raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\n","steps":[{"name":"Вход в систему с зарегистрированными данными (аутентификация)","time":{"start":1730128717331,"stop":1730128746314,"duration":28983},"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 45, in login\n    self.verify_login_success()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 60, in verify_login_success\n    raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\n","steps":[{"name":"Ввод email","time":{"start":1730128717331,"stop":1730128718557,"duration":1226},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Ввод пароля","time":{"start":1730128718557,"stop":1730128719691,"duration":1134},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Нажатие на кнопку Вход","time":{"start":1730128720692,"stop":1730128720743,"duration":51},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Проверка успешного входа","time":{"start":1730128725748,"stop":1730128746314,"duration":20566},"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me\n","statusTrace":"  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 45, in login\n    self.verify_login_success()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 60, in verify_login_success\n    raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\n","steps":[{"name":"Проверка перехода на страницу каналов","time":{"start":1730128725748,"stop":1730128746313,"duration":20565},"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 60, in verify_login_success\n    raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":5,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":6,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":8,"attachmentsCount":0,"hasContent":true}],"testStage":{"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me","statusTrace":"self = <login_page.LoginPage object at 0x7f6331483f70>\n\n    @allure.step(\"Проверка перехода на страницу каналов\")\n    def verify_login_success(self):\n        try:\n>           self.wait_for_url_to_be(LoginPage.CHANNELS_URL, timeout=20)\n\nlogin_page.py:55: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nlogin_page.py:90: in wait_for_url_to_be\n    WebDriverWait(self.driver, timeout).until(EC.url_to_be(url))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"9a7727a07998286cc9dc9bab69a00dab\")>\nmethod = <function url_to_be.<locals>._predicate at 0x7f6331aea8c0>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9a7727a07998286cc9dc9bab69a00dab\")>\n\n    @pytest.fixture(scope=\"class\", autouse=True)\n    def setup(driver):\n        login_page = LoginPage(driver)\n    \n        with allure.step(\"Открытие страницы логина\"):\n            login_page.open(\"https://discord.com/login\")\n    \n            if not login_page.is_element_visible(LoginPage.EMAIL_INPUT):\n                raise AssertionError(\"Поле для ввода email не найдено.\")\n    \n        with allure.step(\"Вход в систему\"):\n>           login_page.login()\n\nconftest.py:58: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nlogin_page.py:45: in login\n    self.verify_login_success()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <login_page.LoginPage object at 0x7f6331483f70>\n\n    @allure.step(\"Проверка перехода на страницу каналов\")\n    def verify_login_success(self):\n        try:\n            self.wait_for_url_to_be(LoginPage.CHANNELS_URL, timeout=20)\n            print(f\"Успешный вход: переход на {LoginPage.CHANNELS_URL}\")\n        except TimeoutException:\n            print(\"Ошибка: Не удалось перейти на страницу каналов после логина\")\n            self.take_screenshot(\"login_failed\")\n>           raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\nE           AssertionError: Не удалось перейти на https://discord.com/channels/@me\n\nlogin_page.py:60: AssertionError","steps":[],"attachments":[{"uid":"3f7b853e465103fd","name":"stdout","source":"3f7b853e465103fd.txt","type":"text/plain","size":1724}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true},"afterStages":[{"name":"driver::0","time":{"start":1730128746388,"stop":1730128746477,"duration":89},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"order(1)"},{"name":"tag","value":"@pytest.mark.usefixtures('setup')"},{"name":"suite","value":"test_DiscordFrontEnd"},{"name":"subSuite","value":"TestDiscordMessageActions"},{"name":"host","value":"fv-az730-34"},{"name":"thread","value":"2089-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_DiscordFrontEnd"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"driver","value":"'chrome'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":2,"broken":11,"skipped":0,"passed":0,"unknown":0,"total":13},"items":[{"uid":"37682e69e8f7da41","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/13//#testresult/37682e69e8f7da41","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730128615897,"stop":1730128615897,"duration":0}},{"uid":"d114d9e1305e3254","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/12//#testresult/d114d9e1305e3254","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730128537376,"stop":1730128537376,"duration":0}},{"uid":"650fc9ef9bf5f699","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/11//#testresult/650fc9ef9bf5f699","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730128005114,"stop":1730128005114,"duration":0}},{"uid":"37420fd28d6ef5f6","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/10//#testresult/37420fd28d6ef5f6","status":"failed","statusDetails":"AssertionError: Не удалось перейти на https://discord.com/channels/@me","time":{"start":1730127376985,"stop":1730127376985,"duration":0}},{"uid":"28f94bdf58de5aab","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/9//#testresult/28f94bdf58de5aab","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730127332060,"stop":1730127332060,"duration":0}},{"uid":"4a1949455412d436","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/8//#testresult/4a1949455412d436","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730127088553,"stop":1730127088553,"duration":0}},{"uid":"b756a27d32d1dc21","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/7//#testresult/b756a27d32d1dc21","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730124437024,"stop":1730124437024,"duration":0}},{"uid":"2f2ef93e696a5158","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/6//#testresult/2f2ef93e696a5158","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730123838214,"stop":1730123838214,"duration":0}},{"uid":"ef7277fe0d91f11c","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/6//#testresult/ef7277fe0d91f11c","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730123682124,"stop":1730123682124,"duration":0}},{"uid":"75c7c0b17ab824db","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/5//#testresult/75c7c0b17ab824db","status":"broken","statusDetails":"TypeError: 'NoneType' object is not iterable","time":{"start":1730123212449,"stop":1730123212449,"duration":0}},{"uid":"97a8add97195605a","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/4//#testresult/97a8add97195605a","status":"broken","statusDetails":"TypeError: 'NoneType' object is not iterable","time":{"start":1730122248085,"stop":1730122248085,"duration":0}},{"uid":"5fb6d94848ec2ce1","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/3//#testresult/5fb6d94848ec2ce1","status":"broken","statusDetails":"TypeError: 'NoneType' object is not iterable","time":{"start":1730121996428,"stop":1730121996428,"duration":0}}]},"tags":["order(1)","@pytest.mark.usefixtures('setup')"]},"source":"d1b6330e6d0136.json","parameterValues":["'chrome'"]}